# Generated by Django 5.1.7 on 2025-03-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nota_parceiros', models.SmallIntegerField()),
                ('descricao_parceiros', models.CharField(blank=True, max_length=300, null=True)),
                ('nota_clientes', models.SmallIntegerField()),
                ('descricao_clientes', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'avaliacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coletas',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('peso_material', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('quantidade_material', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coletas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enderecos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('preco', models.TextField()),
            ],
            options={
                'db_table': 'materiais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('valor_pagamento', models.TextField()),
                ('saldo_pagamento', models.TextField()),
                ('estado_pagamento', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pagamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'parceiros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PontosColeta',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pontos_coleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('estado_solicitacao', models.CharField(max_length=10)),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.TextField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaisParceiros',
            fields=[
                ('id_materiais', models.OneToOneField(db_column='id_materiais', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.materiais')),
            ],
            options={
                'db_table': 'materiais_parceiros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaisPontosColeta',
            fields=[
                ('id_materiais', models.OneToOneField(db_column='id_materiais', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.materiais')),
            ],
            options={
                'db_table': 'materiais_pontos_coleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefones',
            fields=[
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
                ('id_usuarios', models.OneToOneField(db_column='id_usuarios', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.usuarios')),
                ('numero', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'telefones',
                'managed': False,
            },
        ),
    ]
