# Generated by Django 5.1.7 on 2025-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('ponto_coleta', models.CharField(max_length=255)),
            ],
        ),
    ]
