# Generated by Django 5.1.7 on 2025-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_materialdescarte'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdescarte',
            name='reciclavel',
            field=models.BooleanField(default=False),
        ),
    ]
